# Generated by Django 2.2.19 on 2022-05-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220530_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
